{"name": "Проверка ошибки при неверном логине или пароле.Ожидаемый результат: 404", "status": "passed", "parameters": [{"name": "field", "value": "'login'"}, {"name": "invalid_value", "value": "'lwrypgikaj'"}], "start": 1743608242399, "stop": 1743608242493, "uuid": "023fee08-8464-4426-ba63-bff1073c60cc", "historyId": "ff9fcaed14768da35153124064eb2fd5", "testCaseId": "ea9a450ccbd1454b021935fd27407c1e", "fullName": "tests.test_courier_auth.TestCourierAuth#test_authorization_invalid_login_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestCourierAuth"}, {"name": "host", "value": "DESKTOP-O2PS26S"}, {"name": "thread", "value": "28228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}