{"name": "Проверка получения ошибки при неверном логине или пароле", "status": "passed", "parameters": [{"name": "field", "value": "'password'"}, {"name": "invalid_value", "value": "'ishuzmedgj'"}], "start": 1743506903964, "stop": 1743506904047, "uuid": "ef164929-80c3-4a38-8acb-ecd79bb76d90", "historyId": "62862b91d0094c57d070d2136855c6f7", "testCaseId": "80750c2c8f519e9f594a6889a93ae64d", "fullName": "tests.test_courier_auth.TestCourierAuth#test_error_entering_nonexistent_login_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestCourierAuth"}, {"name": "host", "value": "DESKTOP-O2PS26S"}, {"name": "thread", "value": "30688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}