{"name": "Проверка получения ошибки при неверном логине или пароле", "status": "passed", "parameters": [{"name": "field", "value": "'login'"}, {"name": "invalid_value", "value": "'hpyjyxnkeh'"}], "start": 1743506903854, "stop": 1743506903960, "uuid": "8cc3eec0-6517-4bea-a194-1756dadd9407", "historyId": "a2610ce9a197c4b1ef6667a74f062a5c", "testCaseId": "80750c2c8f519e9f594a6889a93ae64d", "fullName": "tests.test_courier_auth.TestCourierAuth#test_error_entering_nonexistent_login_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_auth"}, {"name": "subSuite", "value": "TestCourierAuth"}, {"name": "host", "value": "DESKTOP-O2PS26S"}, {"name": "thread", "value": "30688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_auth"}]}